#ifndef HYBRID_SRC_VERSION_H_
#define HYBRID_SRC_VERSION_H_

#define HYBRID_VERSION_MAJOR 0
#define HYBRID_VERSION_MINOR 1
#define HYBRID_VERSION_MICRO 0
#define HYBRID_VERSION "0.1.0"

#endif  // HYBRID_SRC_VERSION_H_
